First we are importing two popular library, pandas and numpy.

In [90]:
import pandas as pd;
import numpy as np;

Importing dataset from sklearn.

In [91]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()



Printing the keys of iris_dataset

In [92]:
print("Keys Of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys Of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Printing the description of the dataset

In [93]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [94]:
val = iris_dataset['DESCR']
start_val = val[:200]
print( start_val  + "\n")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive



In [95]:
print("Features Name: {}" .format(iris_dataset['target_names']))

Features Name: ['setosa' 'versicolor' 'virginica']


In [96]:
print("Type of data: {}" .format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [97]:
print("Shape of the data: {}" .format(iris_dataset['data'].shape))

Shape of the data: (150, 4)


In [98]:
print("first five rows of the data:\n{}" .format(iris_dataset['data'][:5]))

first five rows of the data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [99]:
print("Target names: {}" .format(iris_dataset['target']))

Target names: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


File location

In [100]:
print("Target: \n{}" . format(iris_dataset['filename']))

Target: 
/usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/iris.csv


Printing the feature names from iris_dataset

In [101]:
print("Feature name: \n{}" .format(iris_dataset['feature_names']))

Feature name: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [102]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0
)

In [103]:
print("X_train shape: {}" .format(X_train.shape))
print("y_train shape: {}" .format(y_train.shape))
print("X_test shape: {}" .format(X_test.shape))
print("y_test shape: {}" .format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


This is the model

In [104]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [105]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski', metric_params=None, n_jobs=None, n_neighbors=5, p=2, weights='uniform')

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

Making Prediction

In [106]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}" .format(X_new.shape))
X_new.shape: (1, 4)

X_new.shape: (1, 4)


In [107]:
prediction = knn.predict(X_new)

print("Prediction: {}" .format(prediction))
print("Predicted target name:{}" .format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name:['setosa']


evaluate our model

In [108]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}" .format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [109]:
print("Test score prediction:\n {}" .format(np.mean(y_test)))

Test score prediction:
 0.8947368421052632


In [110]:
print("Test set score: {}" .format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
